[[redirects]]
  from = "/api/*"
  to = "https://rakshak112-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/events"
  to = "https://rakshak112-backend.onrender.com/api/events"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
